/**
 * Google Doc AI Comments Bot
 *
 * Monitors comments on the bound Google Doc and replies to comments
 * addressed to the bot (@AI, @Bot, @Claude) with context-aware answers
 * generated by Claude.
 *
 * Setup: see README.md (clasp push or manual paste), then run initialSetup().
 *
 * Script Properties (Project Settings > Script Properties):
 *   ANTHROPIC_API_KEY  required
 *   CLAUDE_MODEL       optional, defaults to CONFIG.DEFAULT_MODEL
 */

const CONFIG = {
  BOT_TRIGGERS: ['@ai', '@bot', '@claude'],
  DEFAULT_MODEL: 'claude-sonnet-5',
  MAX_CONTEXT_CHARS: 8000,
  MAX_RESPONSE_TOKENS: 1024,
  CHECK_INTERVAL_MINUTES: 1,
  PROCESSED_KEY_PREFIX: 'processed:',
  ANTHROPIC_URL: 'https://api.anthropic.com/v1/messages',
  ANTHROPIC_VERSION: '2023-06-01'
};

const SYSTEM_PROMPT = [
  'You are a helpful AI assistant responding to comments in a Google Doc.',
  'Your responses will appear as comment replies, so keep them concise but informative.',
  'Be direct and helpful. If you need clarification, ask for it.',
  'Format your response for a comment thread: no excessive markdown, keep it readable.'
].join('\n');

// ============ MAIN ============

/**
 * Entry point for the time-driven trigger: checks comments and replies.
 */
function checkAndReplyToComments() {
  const doc = DocumentApp.getActiveDocument();
  if (!doc) {
    Logger.log('No active document found. Run this from within a Google Doc.');
    return;
  }

  const docId = doc.getId();
  const fullText = doc.getBody().getText();
  const comments = getDocumentComments(docId);

  for (const comment of comments) {
    if (isCommentProcessed(comment.id)) continue;
    if (!isAddressedToBot(comment.content)) continue;

    if (comment.replies && comment.replies.length > 0) {
      markCommentAsProcessed(comment.id);
      continue;
    }

    Logger.log(`Processing comment: ${comment.content}`);

    const highlighted = comment.quotedFileContent ? comment.quotedFileContent.value : null;
    const context = buildContextWindow(fullText, highlighted, CONFIG.MAX_CONTEXT_CHARS);
    const response = generateAIResponse(comment.content, context, highlighted);

    if (response) {
      postReply(docId, comment.id, response);
      Logger.log(`Replied to comment ${comment.id}`);
    }

    markCommentAsProcessed(comment.id);
  }
}

// ============ PURE HELPERS (unit tested in test/) ============

/**
 * True when the comment starts with one of the bot triggers.
 */
function isAddressedToBot(content) {
  if (!content) return false;
  const lower = content.toLowerCase().trim();
  return CONFIG.BOT_TRIGGERS.some((trigger) => lower.startsWith(trigger));
}

/**
 * Removes the leading bot trigger from a comment, returning the question.
 */
function stripTrigger(content) {
  const trimmed = (content || '').trim();
  const lower = trimmed.toLowerCase();
  for (const trigger of CONFIG.BOT_TRIGGERS) {
    if (lower.startsWith(trigger)) {
      return trimmed.substring(trigger.length).trim();
    }
  }
  return trimmed;
}

/**
 * Returns up to maxChars of document text, centred on the quoted text when
 * it can be located, otherwise the beginning of the document.
 */
function buildContextWindow(fullText, quotedText, maxChars) {
  if (fullText.length <= maxChars) return fullText;

  if (quotedText) {
    const index = fullText.indexOf(quotedText);
    if (index !== -1) {
      const padding = Math.max(0, Math.floor((maxChars - quotedText.length) / 2));
      const start = Math.max(0, index - padding);
      const end = Math.min(fullText.length, index + quotedText.length + padding);
      let context = fullText.substring(start, end);
      if (start > 0) context = '...' + context;
      if (end < fullText.length) context = context + '...';
      return context;
    }
  }

  return fullText.substring(0, maxChars) + '...';
}

/**
 * Builds the user message sent to Claude.
 */
function buildUserMessage(question, documentContext, highlightedText) {
  if (highlightedText) {
    return [
      'The user highlighted this text in the document:',
      '---',
      highlightedText,
      '---',
      '',
      `And asked: "${question}"`,
      '',
      'Here is the broader document context for reference:',
      '---',
      documentContext,
      '---',
      '',
      'Please provide a helpful response to their question about the highlighted text.'
    ].join('\n');
  }
  return [
    `The user left this comment on the document: "${question}"`,
    '',
    'Here is the document content for context:',
    '---',
    documentContext,
    '---',
    '',
    'Please provide a helpful response.'
  ].join('\n');
}

// ============ CLAUDE ============

/**
 * Reads the configured model from Script Properties, falling back to the default.
 */
function getModel() {
  const configured = PropertiesService.getScriptProperties().getProperty('CLAUDE_MODEL');
  return configured && configured.trim() ? configured.trim() : CONFIG.DEFAULT_MODEL;
}

/**
 * Single place that talks to the Anthropic Messages API.
 *
 * @param {Object} options
 * @param {string} options.userMessage
 * @param {string} [options.system]
 * @param {number} [options.maxTokens]
 * @returns {{ok: boolean, text?: string, status?: number, error?: string}}
 */
function callClaude(options) {
  const apiKey = PropertiesService.getScriptProperties().getProperty('ANTHROPIC_API_KEY');
  if (!apiKey) {
    return { ok: false, error: 'ANTHROPIC_API_KEY not set in Script Properties' };
  }

  const payload = {
    model: getModel(),
    max_tokens: options.maxTokens || CONFIG.MAX_RESPONSE_TOKENS,
    messages: [{ role: 'user', content: options.userMessage }]
  };
  if (options.system) payload.system = options.system;

  try {
    const response = UrlFetchApp.fetch(CONFIG.ANTHROPIC_URL, {
      method: 'post',
      contentType: 'application/json',
      headers: {
        'x-api-key': apiKey,
        'anthropic-version': CONFIG.ANTHROPIC_VERSION
      },
      payload: JSON.stringify(payload),
      muteHttpExceptions: true
    });

    const status = response.getResponseCode();
    const body = JSON.parse(response.getContentText());
    if (status !== 200) {
      return { ok: false, status: status, error: JSON.stringify(body) };
    }
    const textBlock = (body.content || []).find((block) => block.type === 'text');
    return { ok: true, text: textBlock ? textBlock.text : '' };
  } catch (error) {
    return { ok: false, error: error.message };
  }
}

/**
 * Produces the reply text for a comment, or an error string for the thread.
 */
function generateAIResponse(commentContent, documentContext, highlightedText) {
  const question = stripTrigger(commentContent);
  const result = callClaude({
    system: SYSTEM_PROMPT,
    userMessage: buildUserMessage(question, documentContext, highlightedText)
  });

  if (!result.ok) {
    Logger.log(`Claude error: ${result.error}`);
    return result.status
      ? `Error: Unable to generate response (${result.status})`
      : `Error: ${result.error}`;
  }
  return result.text;
}

// ============ DRIVE ============

/**
 * Unresolved comments on the document, via the Drive advanced service (v3).
 */
function getDocumentComments(docId) {
  try {
    const result = Drive.Comments.list(docId, {
      fields: 'comments(id,content,quotedFileContent,replies(content,author),resolved,author)',
      includeDeleted: false
    });
    return (result.comments || []).filter((c) => !c.resolved);
  } catch (error) {
    Logger.log(`Error fetching comments: ${error.message}`);
    return [];
  }
}

function postReply(docId, commentId, replyContent) {
  try {
    Drive.Replies.create({ content: replyContent }, docId, commentId, { fields: 'id' });
  } catch (error) {
    Logger.log(`Error posting reply: ${error.message}`);
  }
}

// ============ STATE ============
// One Script Property per processed comment avoids the per-value size cap
// that a single JSON array would eventually hit.

function isCommentProcessed(commentId) {
  return PropertiesService.getScriptProperties()
    .getProperty(CONFIG.PROCESSED_KEY_PREFIX + commentId) !== null;
}

function markCommentAsProcessed(commentId) {
  PropertiesService.getScriptProperties()
    .setProperty(CONFIG.PROCESSED_KEY_PREFIX + commentId, new Date().toISOString());
}

/**
 * Forget every processed comment so they can be re-answered (testing aid).
 */
function clearProcessedComments() {
  const props = PropertiesService.getScriptProperties();
  const keys = props.getKeys().filter((k) => k.startsWith(CONFIG.PROCESSED_KEY_PREFIX));
  keys.forEach((k) => props.deleteProperty(k));
  Logger.log(`Cleared ${keys.length} processed comment marker(s)`);
}

// ============ SETUP ============

function setupTrigger() {
  removeTriggers();
  ScriptApp.newTrigger('checkAndReplyToComments')
    .timeDriven()
    .everyMinutes(CONFIG.CHECK_INTERVAL_MINUTES)
    .create();
  Logger.log(`Trigger set up to run every ${CONFIG.CHECK_INTERVAL_MINUTES} minute(s)`);
}

function removeTriggers() {
  ScriptApp.getProjectTriggers().forEach((t) => ScriptApp.deleteTrigger(t));
  Logger.log('All triggers removed');
}

/**
 * Run this first: verifies the API key and installs the trigger.
 */
function initialSetup() {
  const apiKey = PropertiesService.getScriptProperties().getProperty('ANTHROPIC_API_KEY');
  if (!apiKey) {
    Logger.log('SETUP REQUIRED: set ANTHROPIC_API_KEY in Project Settings > Script Properties.');
    return;
  }
  Logger.log(`API key configured. Model: ${getModel()}`);
  setupTrigger();
  Logger.log('Setup complete. Add a comment starting with @AI to test.');
}

function testRun() {
  Logger.log('Running manual check...');
  checkAndReplyToComments();
  Logger.log('Done!');
}

function testAPIConnection() {
  const result = callClaude({
    userMessage: 'Say "API connection successful!" and nothing else.',
    maxTokens: 50
  });
  Logger.log(result.ok ? `SUCCESS: ${result.text}` : `ERROR: ${result.error}`);
}
